name: cardblaze
description: CardBlaze - Flashcard app with AI generation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.4

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Navigation
  go_router: ^14.8.1

  # Utils
  path_provider: ^2.1.4

  # Network
  http: ^1.2.2

  # Storage
  flutter_secure_storage: ^11.2.0

  # Revenue
  purchases_flutter: ^10.13.1

  # Widget
  home_widget: ^0.10.0

  # PDF & DOCX
  syncfusion_flutter_pdf: ^34.2.8
  file_picker: ^13.1.0
  archive: ^4.0.7
  xml: ^7.0.1

  # Charts
  fl_chart: ^1.2.0

  # Localization
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.0
  timezone: ^0.10.1
  shared_preferences: ^2.5.5
  package_info_plus: ^10.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

  # Code generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
